# Napravi tabelu opstina

DROP TABLE IF EXISTS municipality;

CREATE TABLE municipality (
   id MEDIUMINT UNSIGNED NOT NULL,
   naziv VARCHAR(50) NOT NULL,
   districtID SMALLINT UNSIGNED NOT NULL,
   PRIMARY KEY (id)
);

INSERT INTO municipality (id, naziv, districtID) VALUES (0, 'Није изабрана', 0);
INSERT INTO municipality (id, naziv, districtID) VALUES (70092, 'Београд-Барајево', 0);             
INSERT INTO municipality (id, naziv, districtID) VALUES (70106, 'Београд-Вождовац', 0);
INSERT INTO municipality (id, naziv, districtID) VALUES (70114, 'Београд-Врачар', 0);               
INSERT INTO municipality (id, naziv, districtID) VALUES (70122, 'Београд-Гроцка', 0);               
INSERT INTO municipality (id, naziv, districtID) VALUES (70149, 'Београд-Звездара', 0);             
INSERT INTO municipality (id, naziv, districtID) VALUES (70157, 'Београд-Земун', 0);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70165, 'Београд-Лазаревац', 0);            
INSERT INTO municipality (id, naziv, districtID) VALUES (70173, 'Београд-Младеновац', 0);           
INSERT INTO municipality (id, naziv, districtID) VALUES (70181, 'Београд-Нови Београд', 0);         
INSERT INTO municipality (id, naziv, districtID) VALUES (70190, 'Београд-Обреновац', 0);            
INSERT INTO municipality (id, naziv, districtID) VALUES (70203, 'Београд-Палилула', 0);             
INSERT INTO municipality (id, naziv, districtID) VALUES (70211, 'Београд-Раковица', 0);             
INSERT INTO municipality (id, naziv, districtID) VALUES (70220, 'Београд-Савски Венац', 0);         
INSERT INTO municipality (id, naziv, districtID) VALUES (70238, 'Београд-Сопот', 0);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70246, 'Београд-Стари Град', 0);           
INSERT INTO municipality (id, naziv, districtID) VALUES (70254, 'Београд-Чукарица', 0);             
INSERT INTO municipality (id, naziv, districtID) VALUES (71293, 'Београд-Сурчин', 0);               
INSERT INTO municipality (id, naziv, districtID) VALUES (80071, 'Бачка Топола', 1);                 
INSERT INTO municipality (id, naziv, districtID) VALUES (80241, 'Мали Иђош', 1);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (80438, 'Суботица-град', 1);                
INSERT INTO municipality (id, naziv, districtID) VALUES (80144, 'Житиште', 2);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (80152, 'Зрењанин-град', 2);                
INSERT INTO municipality (id, naziv, districtID) VALUES (80250, 'Нова Црња', 2);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (80268, 'Нови Бечеј', 2);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (80373, 'Сечањ', 2);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (80012, 'Ада', 3);                          
INSERT INTO municipality (id, naziv, districtID) VALUES (80195, 'Кањижа', 3);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (80209, 'Кикинда', 3);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (80276, 'Нови Кнежевац', 3);                
INSERT INTO municipality (id, naziv, districtID) VALUES (80365, 'Сента', 3);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (80489, 'Чока', 3);                         
INSERT INTO municipality (id, naziv, districtID) VALUES (80039, 'Алибунар', 4);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (80098, 'Бела Црква', 4);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (80128, 'Вршац', 4);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (80217, 'Ковачица', 4);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (80225, 'Ковин', 4);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (80292, 'Опово', 4);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (80314, 'Панчево-град', 4);                 
INSERT INTO municipality (id, naziv, districtID) VALUES (80349, 'Пландиште', 4);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (80047, 'Апатин', 5);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (80233, 'Кула', 5);                         
INSERT INTO municipality (id, naziv, districtID) VALUES (80306, 'Оџаци', 5);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (80381, 'Сомбор-град', 5);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (80519, 'Петроварадин', 6);                 
INSERT INTO municipality (id, naziv, districtID) VALUES (80284, 'Нови Сад', 6);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (80055, 'Бач', 6);                          
INSERT INTO municipality (id, naziv, districtID) VALUES (80063, 'Бачка Паланка', 6);                
INSERT INTO municipality (id, naziv, districtID) VALUES (80080, 'Бачки Петровац', 6);               
INSERT INTO municipality (id, naziv, districtID) VALUES (80101, 'Беочин', 6);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (80110, 'Бечеј', 6);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (80136, 'Жабаљ', 6);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (80390, 'Србобран', 6);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (80411, 'Сремски Карловци', 6);             
INSERT INTO municipality (id, naziv, districtID) VALUES (80446, 'Темерин', 6);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (80454, 'Тител', 6);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (80462, 'Врбас', 6);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (80179, 'Инђија', 7);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (80187, 'Ириг', 7);                         
INSERT INTO municipality (id, naziv, districtID) VALUES (80322, 'Пећинци', 7);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (80357, 'Рума', 7);                         
INSERT INTO municipality (id, naziv, districtID) VALUES (80403, 'Сремска Митровица-град', 7);       
INSERT INTO municipality (id, naziv, districtID) VALUES (80420, 'Стара Пазова', 7);                 
INSERT INTO municipality (id, naziv, districtID) VALUES (80497, 'Шид', 7);                          
INSERT INTO municipality (id, naziv, districtID) VALUES (70289, 'Богатић', 8);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (70408, 'Владимирци', 8);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (70637, 'Коцељева', 8);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (70661, 'Крупањ', 8);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (70734, 'Лозница-град', 8);                 
INSERT INTO municipality (id, naziv, districtID) VALUES (70777, 'Љубовија', 8);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (70793, 'Мали Зворник', 8);                 
INSERT INTO municipality (id, naziv, districtID) VALUES (71269, 'Шабац-град', 8);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (70360, 'Ваљево-град', 9);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (70700, 'Лајковац', 9);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (70769, 'Љиг', 9);                          
INSERT INTO municipality (id, naziv, districtID) VALUES (70831, 'Мионица', 9);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (70882, 'Осечина', 9);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (71218, 'Уб', 9);                           
INSERT INTO municipality (id, naziv, districtID) VALUES (70386, 'Велика Плана', 10);                
INSERT INTO municipality (id, naziv, districtID) VALUES (71099, 'Смедерево-град', 10);              
INSERT INTO municipality (id, naziv, districtID) VALUES (71102, 'Смедеревска Паланка', 10);         
INSERT INTO municipality (id, naziv, districtID) VALUES (70947, 'Пожаревац', 11);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (71340, 'Костолац', 11);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (70394, 'Велико Градиште', 11);             
INSERT INTO municipality (id, naziv, districtID) VALUES (70475, 'Голубац', 11);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (70521, 'Жабари', 11);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (70530, 'Жагубица', 11);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (70696, 'Кучево', 11);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (70807, 'Мало Црниће', 11);                 
INSERT INTO municipality (id, naziv, districtID) VALUES (70912, 'Петровац на Млави', 11);           
INSERT INTO municipality (id, naziv, districtID) VALUES (70033, 'Аранђеловац', 12);                 
INSERT INTO municipality (id, naziv, districtID) VALUES (70076, 'Баточина', 12);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (70599, 'Кнић', 12);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (70645, 'Крагујевац-град', 12);             
INSERT INTO municipality (id, naziv, districtID) VALUES (71013, 'Рача', 12);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (71153, 'Топола', 12);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (71277, 'Лапово', 12);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (70491, 'Деспотовац', 13);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (70904, 'Параћин', 13);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (71030, 'Рековац', 13);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (71048, 'Јагодина-град', 13);               
INSERT INTO municipality (id, naziv, districtID) VALUES (71056, 'Свилајнац', 13);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (71200, 'Ћуприја', 13);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (70327, 'Бор', 14);                         
INSERT INTO municipality (id, naziv, districtID) VALUES (70572, 'Кладово', 14);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (70785, 'Мајданпек', 14);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (70840, 'Неготин', 14);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (70319, 'Бољевац', 15);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (70556, 'Зајечар-град', 15);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70602, 'Књажевац', 15);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (71129, 'Сокобања', 15);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (70041, 'Ариље', 16);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (70068, 'Бајина Башта', 16);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70629, 'Косјерић', 16);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (70866, 'Нова Варош', 16);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (70955, 'Пожега', 16);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (70971, 'Прибој', 16);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (70980, 'Пријепоље', 16);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (71072, 'Сјеница', 16);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (71145, 'Ужице-град', 16);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (71234, 'Чајетина', 16);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (70483, 'Горњи Милановац', 17);             
INSERT INTO municipality (id, naziv, districtID) VALUES (70564, 'Ивањица', 17);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (70742, 'Лучани', 17);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (71242, 'Чачак-град', 17);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (70459, 'Врњачка Бања', 18);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70653, 'Краљево-град', 18);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70874, 'Нови Пазар-град', 18);             
INSERT INTO municipality (id, naziv, districtID) VALUES (71021, 'Рашка', 18);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (71188, 'Тутин', 18);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (70017, 'Александровац', 19);               
INSERT INTO municipality (id, naziv, districtID) VALUES (70343, 'Брус', 19);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (70378, 'Варварин', 19);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (70670, 'Крушевац-град', 19);               
INSERT INTO municipality (id, naziv, districtID) VALUES (71170, 'Трстеник', 19);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (71196, 'Ћићевац', 19);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (71285, 'Нишка Бања', 20);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (71307, 'Ниш-Пантелеј', 20);                
INSERT INTO municipality (id, naziv, districtID) VALUES (71315, 'Ниш-Црвени Крст', 20);             
INSERT INTO municipality (id, naziv, districtID) VALUES (71323, 'Ниш-Палилула', 20);                
INSERT INTO municipality (id, naziv, districtID) VALUES (71331, 'Ниш-Медиjана', 20);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70025, 'Алексинац', 20);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (70467, 'Гаџин Хан', 20);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (70513, 'Дољевац', 20);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (70823, 'Мерошина', 20);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (71005, 'Ражањ', 20);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (71064, 'Сврљиг', 20);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (70262, 'Блаце', 21);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (70548, 'Житорађа', 21);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (70688, 'Куршумлија', 21);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (70998, 'Прокупље', 21);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (70050, 'Бабушница', 22);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (70084, 'Бела Паланка', 22);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70505, 'Димитровград', 22);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70939, 'Пирот', 22);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (70297, 'Бојник', 23);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (70424, 'Власотинце', 23);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (70718, 'Лебане', 23);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (70726, 'Лесковац-град', 23);               
INSERT INTO municipality (id, naziv, districtID) VALUES (70815, 'Медвеђа', 23);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (71226, 'Црна Трава', 23);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (70432, 'Врање', 24);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (71358, 'Врањска Бања', 24);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70335, 'Босилеград', 24);                  
INSERT INTO municipality (id, naziv, districtID) VALUES (70351, 'Бујановац', 24);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (70416, 'Владичин Хан', 24);                
INSERT INTO municipality (id, naziv, districtID) VALUES (70963, 'Прешево', 24);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (71137, 'Сурдулица', 24);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (71161, 'Трговиште', 24);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (90034, 'Глоговац', 25);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (90115, 'Качаник', 25);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (90131, 'Косово Поље', 25);                 
INSERT INTO municipality (id, naziv, districtID) VALUES (90166, 'Липљан', 25);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (90204, 'Обилић', 25);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (90247, 'Подујево', 25);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (90263, 'Приштина-град', 25);               
INSERT INTO municipality (id, naziv, districtID) VALUES (90301, 'Урошевац', 25);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (90310, 'Штимље', 25);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (90328, 'Штрпце', 25);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (90069, 'Дечани', 26);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (90085, 'Ђаковица', 26);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (90107, 'Исток', 26);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (90123, 'Клина', 26);                       
INSERT INTO municipality (id, naziv, districtID) VALUES (90239, 'Пећ', 26);                         
INSERT INTO municipality (id, naziv, districtID) VALUES (90212, 'Ораховац', 27);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (90255, 'Призрен', 27);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (90280, 'Сува Река', 27);                   
INSERT INTO municipality (id, naziv, districtID) VALUES (90336, 'Гора', 27);                        
INSERT INTO municipality (id, naziv, districtID) VALUES (90026, 'Вучитрн', 28);                    
INSERT INTO municipality (id, naziv, districtID) VALUES (90093, 'Зубин Поток', 28);                 
INSERT INTO municipality (id, naziv, districtID) VALUES (90158, 'Лепосавић', 28);           
INSERT INTO municipality (id, naziv, districtID) VALUES (90271, 'Србица', 28);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (90298, 'Косовска Митровица', 28);          
INSERT INTO municipality (id, naziv, districtID) VALUES (90352, 'Звечан', 28);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (90018, 'Витина', 29);                      
INSERT INTO municipality (id, naziv, districtID) VALUES (90042, 'Гњилане', 29);                     
INSERT INTO municipality (id, naziv, districtID) VALUES (90140, 'Косовска Каменица', 29);           
INSERT INTO municipality (id, naziv, districtID) VALUES (90182, 'Ново Брдо', 29);                   
